### ISSUE TITLE
Scottish political parties

### ISSUE THREAD

**Issue by james3** [mysociety/yournextrepresentative#776] opened 2016-04-01 16:07 UTC
Adding candidates and it seems I can only select parties from a drop down list. In Scotland candidates officially run as "Scottish Conservative and Unionist Party" and "Scottish Liberal Democrats" rather than "Conservative Party" and "Liberal Democrats". Are these being added or are the UK counterpart party names to be used?

**Comment by andylolz** [comment] 2016-04-01 16:29
> In Scotland candidates officially run as "Scottish Conservative and Unionist Party" and "Scottish Liberal Democrats"

That’s right – "Scottish Conservative and Unionist Party" and "Scottish Liberal Democrats" are party ‘descriptions’ that are registered with the Electoral Commission. It’s the description (rather than the party name) that appears on the ballot paper. For instance, here’s the [registration details for the Liberal Democrats](http://search.electoralcommission.org.uk/English/Registrations/PP90) (they also have “Welsh Liberal Democrats - Democratiaid Rhyddfrydol Cymru”).

YourNextRepresentative currently shows party names rather than descriptions. There’s an issue about this already (#315) but it’s not part of the current sprint. I agree it would be great to sort it, though.

**Comment by mhl** [comment] 2017-04-20 14:46
I'm closing this as a duplicate of #315

**Closed by mhl** 2017-04-20 14:46 UTC
